available_graph_types: !!set { classic, random }
available_topologies:
  classic:
    - complete
    - star
    - cycle
    - grid
  random:
    - erdos_renyi

topology:
  complete:
    type: classic
    object: nx.generators.classic
    func: complete_graph
    bias: False

  star:
    type: classic
    object: nx.generators.classic
    func: star_graph
    bias: True

  cycle:
    type: classic
    object: nx.generators.classic
    func: cycle_graph
    bias: False

  erdos_renyi:
    type: random
    object: nx.generators.random_graphs
    func: fast_gnp_random_graph
    bias: False

  # grid:
  #   type: classic
  #   object: nx.generators.lattice
  #   func: grid_graph
  #   bias: False
  grid:
    type: classic
    object: self
    func: grid_graph
    bias: False

schema:
  - !!python/tuple [
      { topology: str, directed: bool, fixed: bool, MST: bool, plot: bool },

      !!python/tuple [
        { args: {} },
        {
          args:
            {
              p: "And(float, Use(lambda x: x > 0 and x < 1))",
              seed: "And(int, Use(lambda n: n > 0))",
            },
        },
        { args: { periodic: bool } },
      ],
    ]

  - !!python/tuple [state, Or(*self.schema_types)]

  - !!python/tuple [default_state, Or(*self.schema_types)]

  - !!python/tuple [
      default_epoch,
      {
        duration: "And(Use(int), lambda n: n > 0)",
        default_state: self.schema_default_state,
        states: "Or({}, {And(Use(int), lambda n: n >= 0): self.schema_state})",
      },
    ]

  - !!python/tuple [
      epoch,
      {
        interval: tuple,
        default_state: self.schema_default_state,
        states: "Or({}, {And(Use(int), lambda n: n >= 0): self.schema_state})",
      },
    ]
