
argument:
  primal:
    distance_to_consensus:
      source: z_list
      target: z_list
      distance: saddle-con
      step: 1
      verbose: False

    distance_to_opt:
      source: z
      target: z_true
      distance: saddle-2-norm
      step: 1
      verbose: False

gradient:
  primal:
    distance_to_opt:
      source: grad_list_z
      target: g_true
      distance: saddle-grad-norm
      step: 1
      verbose: False