default_epoch:
  duration: 2
  default_state:
    topology: complete
    directed: False
    fixed: True
    MST: True
    plot: False
    args: {}
  states: {}
epochs:
  - interval: !!python/tuple [1, 4]
    default_state:
      topology: complete
      directed: False
      fixed: True
      MST: True
      plot: True
      args: {}
    states:
      1:
        topology: complete
        directed: False
        fixed: True
        MST: False
        plot: True
        args: {}
      3:
        topology: erdos_renyi
        directed: False
        fixed: True
        MST: True
        plot: True
        args:
          p: 0.9
          seed: 30
